version: '3.8'

services:
  local_db:
    env_file:
      - config/docker/.env
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build: .

    image: django_crib:latest

    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - local_db
    env_file:
      - config/docker/.env

  daphne:
    image: django_crib:latest
    command: daphne -u /tmp/daphne.sock config.asgi:application
    volumes:
      - .:/app
    depends_on:
      - local_db
    env_file:
      - config/docker/.env
    ports:
      - "8001:8001"

  celery:
    image: django_crib:latest
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - local_db
      - redis
    env_file:
      - config/docker/.env

  celery_beat:
    image: django_crib:latest
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - local_db
      - redis
    env_file:
      - config/docker/.env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./static:/static/
      - ./nginx:/etc/nginx/conf.d
      - ./log/nginx:/var/log/nginx
    depends_on:
      - web

volumes:
  postgres_data: