version: '3.8'

services:
  local_db:
    env_file:
      - config/docker/.env  # Укажите путь к вашему .env файлу
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  web:
    build: .

    image: django_crib:latest

    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - local_db
    env_file:
      - config/docker/.env  # Укажите путь к вашему .env файлу
    #environment:
    #  - DEBUG=1
    #  - DJANGO_SECRET_KEY=your_secret_key
    #  - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    #  - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase


  daphne:
    image: django_crib:latest
    command: daphne -u /tmp/daphne.sock config.asgi:application
    volumes:
      - .:/app
    depends_on:
      - local_db
    env_file:
      - config/docker/.env
    ports:
      - "8001:8001"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./static:/static/
      - ./nginx:/etc/nginx/conf.d
      - ./log/nginx:/var/log/nginx
    depends_on:
      - web

volumes:
  postgres_data: